site_name: napari-{{cookiecutter.plugin_name}}
site_description: {{cookiecutter.short_description}}
site_author: {{cookiecutter.full_name}}

theme: readthedocs

repo_url: https://github.com/{{cookiecutter.github_username}}/napari-{{cookiecutter.plugin_name}}

pages:
- Home: index.md
